accounts/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path('', views.dashboard, name='account'),
    path('dashboard/', views.dashboard, name='add_cart'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('wishlist/', views.wishlist, name='wishlist'),
]

carts/urls.py
from django.urls import path

from . import views, api

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),

    path('api/add_cart/<int:product_id>/', api.add_cart, name='api_add_cart'),
    path('api/update_cart/', api.update_cart, name='api_update_cart'),

    path('remove_cart/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
    
]

molla_theme/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    
    path('store/', include('store.urls')),
    path('carts/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.error_404

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('place_order/', views.place_order, name='place_order'),
    # path('payments/', views.payments, name='payments'),
    # path('order_complete/', views.order_complete, name='order_complete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser

from store.models import Product

# Create your models here.


class MyAccountManager(BaseUserManager):
    def create_user(self, full_name, email, password=None):
        if not email:
            raise ValueError('Email is required')
        if not full_name:
            raise ValueError('User name is required')

        user = self.model(
            # nomarlize_email để coi test@test.com với test@TEST.com là như nhau
            # Vì bình thường thì domain là case-insensitive
            email=self.normalize_email(email=email),
            full_name=full_name,
        )
        user.set_password(password)

        user.save(using=self._db)
        return user

    def create_superuser(self, full_name, email, password):
        user = self.create_user(
            email=self.normalize_email(email=email),
            full_name=full_name,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True

        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    full_name = models.CharField(max_length=100)
    email = models.CharField(max_length=50, unique=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    province = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)

    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'    # Login field
    REQUIRED_FIELDS = ['full_name']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class Wishlist(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)

    def __str__(self):
        return self.product.product_name

orders/models.py
from django.db import models

from accounts.models import Account
from store.models import Product, Variation
# Create your models here.


class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)

    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20)

    full_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)

    address = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    
    order_note = models.CharField(max_length=100, blank=True)
    order_total = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    is_ordered = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.order_number
        

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(
        Payment,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

accounts/views.py
from re import split
from carts.models import Cart, CartItem
from django.shortcuts import redirect, render
from django.contrib import messages, auth
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator

from accounts.models import Account, Wishlist
from orders.models import Order
from carts.views import _cart_id

import requests
# Create your views here.


def login(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == "POST":
        email = request.POST.get('email').lower()
        password = request.POST.get('password')
        user = auth.authenticate(email=email, password=password)
        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                cart_items = CartItem.objects.filter(cart=cart)
                if cart_items.exists():
                    product_variation = []
                    for cart_item in cart_items:
                        variations = cart_item.variations.all()
                        product_variation.append(list(variations))

                    cart_items = CartItem.objects.filter(cart__user=user)
                    existing_variation_list = [list(item.variations.all()) for item in cart_items]
                    id = [item.id for item in cart_items]

                    for product in product_variation:
                        if product in existing_variation_list:
                            index = existing_variation_list.index(product)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_items = CartItem.objects.filter(cart=cart)
                            for item in cart_items:
                                item.user = user
                                item.save()
            except Exception:
                pass
            auth.login(request=request, user=user)
            messages.success(request=request, message="Login successful!")

            url = request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query
                params = dict(x.split("=") for x in query.split("&"))
                if "next" in params:
                    next_page = params["next"]
                    return redirect(next_page)
            except Exception:
                return redirect('account')
        else:
            messages.error(request=request, message="Login failed!")

    else:
        print('Error')

    context = {
        
    }
    return render(request, 'accounts/login.html', context=context)


def signup(request):
    print(request)
    if request.method == 'POST':
        form = request.POST

        full_name = form['full_name']
        email = form['email']
        password = form['password']
        password_confirmation = form['password_confirmation']
        print(full_name, email, password, password_confirmation)

        if password == password_confirmation:
            user = Account.objects.create_user(
                full_name=full_name,
                email=email,
                password=password
            )
            user.save()

            auth.login(request, user)
            return redirect('home')
        else:
            print('Password do not match')
    else:
        print('Error')
        return redirect('store')

    return redirect('login')


@login_required(login_url='login')
def dashboard(request):
    current_user = request.user
    orders = Order.objects.filter(user=current_user).order_by('-created_at')
    address = current_user.address
    province = current_user.province
    city = current_user.city

    context = {
        'user': current_user,
        'orders': orders,
        'address': address,
        'province': province,
        'city': city,
    }

    return render(request, 'accounts/account.html', context)


@login_required(login_url='login')
def logout(request):
    auth.logout(request)
    return redirect('home')


@login_required(login_url='login')
def wishlist(request):
    userWishlist = Wishlist.objects.filter(user=request.user)
    context = {
        'wishlist': userWishlist,
    }

    return render(request, 'accounts/wishlist.html', context)


@login_required(login_url='login')
def add_wishlist(request):
    
    return redirect('wishlist')

orders/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from carts.models import CartItem
# from .forms import OrderForm
import datetime
from carts.views import get_cart
from .models import Order, Payment, OrderProduct
from store.models import Product
from django.core.mail import EmailMessage
from django.template.loader import render_to_string


def sendEmail(request, order):
    mail_subject = 'Thank you for your order!'
    message = render_to_string('orders/order_recieved_email.html', {
        'user': request.user,
        'order': order
    })
    to_email = request.user.email
    send_email = EmailMessage(mail_subject, message, to=[to_email])
    send_email.send()


# def payments(request):
#     try:
#         if request.is_ajax() and request.method == 'POST':
#             data = request.POST
#             order_id = data['orderID']
#             trans_id = data['transID']
#             payment_method = data['payment_method']
#             status = data['status']

#             # Lấy bản ghi order
#             order = Order.objects.get(
#                 user=request.user, is_ordered=False, order_number=order_id)
#             # Tạo 1 bản ghi payment
#             payment = Payment(
#                 user=request.user,
#                 payment_id=trans_id,
#                 payment_method=payment_method,
#                 amount_paid=order.order_total,
#                 status=status,
#             )
#             payment.save()

#             order.payment = payment
#             order.is_ordered = True
#             order.save()

#             # Chuyển hết cart_item thành order_product
#             cart_items = CartItem.objects.filter(user=request.user)
#             for item in cart_items:
#                 order_product = OrderProduct()
#                 order_product.order_id = order.id
#                 order_product.payment = payment
#                 order_product.user_id = request.user.id
#                 order_product.product_id = item.product_id
#                 order_product.quantity = item.quantity
#                 order_product.product_price = item.product.price
#                 order_product.ordered = True
#                 order_product.save()

#                 cart_item = CartItem.objects.get(id=item.id)
#                 product_variation = cart_item.variations.all()
#                 order_product = OrderProduct.objects.get(id=order_product.id)
#                 order_product.variations.set(product_variation)
#                 order_product.save()

#                 # Reduce the quantity of the sold products
#                 product = Product.objects.get(id=item.product_id)
#                 product.stock -= item.quantity
#                 product.save()

#             # Xóa hết cart_item
#             CartItem.objects.filter(user=request.user).delete()

#             # Gửi thư cảm ơn
#             sendEmail(request=request, order=order)

#             # Phản hồi lại ajax
#             data = {
#                 'order_number': order.order_number,
#                 'transID': payment.payment_id,
#             }
#         return JsonResponse({"data": data}, status=200)
#     except Exception as e:
#         return JsonResponse({"error": e}, status=400)


def place_order(request, total=0, quantity=0,):

    # If the cart count is less than or equal to 0, then redirect back to shop
    cart = get_cart(request)
    cart_items = CartItem.objects.filter(cart=cart)

    if cart_items.count() <= 0:
        return redirect('store')

    grand_total = 0

    for cart_item in cart_items:
        total += cart_item.sub_total()
        quantity += cart_item.quantity
    grand_total = total

    if request.method == 'POST':
        print(request.POST)
        form = request.POST

        # Store all the billing information inside Order table
        data = Order()
        data.user = request.user
        data.full_name = form['full_name']
        data.phone = form['phone_number']
        data.email = form['email']

        data.address = form['address']
        data.province = form['province']
        data.city = form['city']

        data.order_note = form['order_note']
        data.order_total = grand_total
        data.ip = request.META.get('REMOTE_ADDR')
        data.save()

        # Generate order number
        yr = int(datetime.date.today().strftime('%Y'))
        mt = int(datetime.date.today().strftime('%m'))
        dt = int(datetime.date.today().strftime('%d'))
        d = datetime.date(yr, mt, dt)
        current_date = d.strftime("%Y%m%d")         # 20210305
        order_number = current_date + str(data.id)
        data.order_number = order_number
        data.is_ordered = True
        
        data.save()

        # Move all cart items into ordered items
        order = Order.objects.get(order_number=data.order_number)

        for item in cart_items:
            order_product = OrderProduct()
            order_product.order = order
            order_product.product = item.product
            order_product.quantity = item.quantity
            order_product.product_price = item.product.price
            order_product.ordered = True

            order_product.save()

            product_variation = item.variations.all()
            order_product.variations.set(product_variation)
            
            order_product.save()

            # Reduce the quantity of the sold products
            product = Product.objects.get(id=item.product_id)
            product.stock -= item.quantity
            product.save()

            # Clear cart items
            CartItem.objects.filter(cart=cart).delete()

            # Send thank you mail
            # sendEmail(request=request, order=order)

        return redirect('account')
    
    else:
        return redirect('checkout')

accounts/templates/accounts/include/account_details.html
<div class="tab-pane fade" id="tab-account" role="tabpanel" aria-labelledby="tab-account-link">
  <form action="#">
    <label>Full name *</label>
    <input type="text" class="form-control" value="{{ user.full_name }}" required>

    <label>Email address *</label>
    <input type="email" class="form-control" value="{{ user.email }}" required>

    <label>Current password (leave blank to leave unchanged)</label>
    <input type="password" class="form-control">

    <label>New password (leave blank to leave unchanged)</label>
    <input type="password" class="form-control">

    <label>Confirm new password</label>
    <input type="password" class="form-control mb-2">

    <button type="submit" class="btn btn-outline-primary-2">
      <span>SAVE CHANGES</span>
      <i class="icon-long-arrow-right"></i>
    </button>
  </form>
</div><!-- .End .tab-pane -->

accounts/templates/accounts/include/addresses.html
<div class="tab-pane fade" id="tab-address" role="tabpanel" aria-labelledby="tab-address-link">
  <p>The following addresses will be used on the checkout page by default.</p>

  <div class="row">
    <div class="col-lg-12">
      <div class="card card-dashboard">
        <div class="card-body">
          <h3 class="card-title">Shipping Address</h3><!-- End .card-title -->

          {% if address is not None %}

          <p>  
            <div>Địa chỉ:  {{ address }}</div>
            <div>Quận/Huyện:  {{ province }}</div>
            <div>Thành phố/Tỉnh:  {{ city }}</div>
          </p>

          {% else %}

          <p>You have not set up this type of address yet.<br>
            <a href="#">Edit <i class="icon-edit"></i></a>
          </p>

          {% endif %}

        </div><!-- End .card-body -->
      </div><!-- End .card-dashboard -->
    </div><!-- End .col-lg-6 -->
  </div><!-- End .row -->
</div><!-- .End .tab-pane -->

accounts/templates/accounts/include/dashboard.html
{% load humanize %}

<div class="tab-pane fade show active" id="tab-dashboard" role="tabpanel" aria-labelledby="tab-dashboard-link">
  <p>Hello <span class="font-weight-normal text-dark">{{ user.full_name }}</span> (not <span
      class="font-weight-normal text-dark">{{ user.full_name }}</span>? <a href="#">Log out</a>)
    <br>
    From your account dashboard you can view your <a href="#tab-orders" class="tab-trigger-link link-underline">recent
      orders</a>, manage your <a href="#tab-address" class="tab-trigger-link">shipping and billing addresses</a>, and <a
      href="#tab-account" class="tab-trigger-link">edit your password and account details</a>.
  </p>
  
  {% if orders.count > 0 %}

  <h4 class="my-5 text-dark">Các đơn hàng gần đây</h4>
  
  {% with orders|slice:"2" as filter_orders%}
  {% for order in filter_orders %}
  <div class="mb-5" id="accordion-{{ order.order_number }}">
    <div class="card card-box card-sm bg-light ">
      <div class="card-header" id="heading{{ order.order_number }}-1">
        <h2 class="card-title">
          <a role="button" data-toggle="collapse" href="#collapse{{ order.order_number }}-1" aria-expanded="true"
            aria-controls="collapse5-1">
            ID Đơn hàng: <span>{{ order.order_number }}</span>
          </a>
        </h2>
      </div><!-- End .card-header -->

      <div id="collapse{{ order.order_number }}-1" class="collapse {% if forloop.counter == 1 %}show{% endif %}"
        aria-labelledby="heading{{ order.order_number }}-1" data-parent="#accordion-{{ order.order_number }}">
        <div class="card-body">

          <p>Trạng thái đơn hàng: <span>{{ order.status }}</span></p>

          <table class="table table-orders table-mobile">
            <tbody>

              {% for order_item in order.orderproduct_set.all %}
              <tr>
                <td class="product-col">
                  <div class="product">
                    <figure class="product-media">
                      <a href="{{ order_item.product.get_url }}">
                        <img src="{{ order_item.product.images.url }}" alt="Product image">
                      </a>
                    </figure>

                    <h3 class="product-title">
                      <a href="{{ order_item.product.get_url }}">{{ order_item.product }}</a>
                    </h3><!-- End .product-title -->
                  </div><!-- End .product -->
                </td>
                <td class="quantity-col">x {{ order_item.quantity }}</td>
                <td class="price-col">
                  {% if order_item.product.discount_price %}
                  <span class="new-price">{{ order_item.product.discount_price|intcomma }} đ</span>
                  <span class="old-price">{{ order_item.product.price|intcomma }} đ</span>
                  {% else %}
                  {{ order_item.product.price|intcomma }} đ
                  {% endif %}
                </td>
              </tr>
              {% endfor %}

            </tbody>
          </table><!-- End .table table-orders -->
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  {% endwith %}

  {% endif %}
</div>

accounts/templates/accounts/include/orders.html
{% load humanize %}

<div class="tab-pane fade" id="tab-orders" role="tabpanel" aria-labelledby="tab-orders-link">
  {% if orders.count > 0 %}

  {% for order in orders%}
  <div class="mb-5" id="accordion-{{ order.order_number }}">
    <div class="card card-box card-sm bg-light ">
      <div class="card-header" id="heading{{ order.order_number }}-1">
        <h2 class="card-title">
          <a role="button" data-toggle="collapse" href="#collapse{{ order.order_number }}-1" aria-expanded="true" aria-controls="collapse5-1">
            ID Đơn hàng: <span>{{ order.order_number }}</span>
          </a>
        </h2>
      </div><!-- End .card-header -->
      
      <div id="collapse{{ order.order_number }}-1" class="collapse show" aria-labelledby="heading{{ order.order_number }}-1" data-parent="#accordion-{{ order.order_number }}">
        <div class="card-body">

          <p>Trạng thái đơn hàng: <span>{{ order.status }}</span></p>

          <table class="table table-orders table-mobile">
            <tbody>

              {% for order_item in order.orderproduct_set.all %}
              <tr>
                <td class="product-col">
                  <div class="product">
                    <figure class="product-media">
                      <a href="{{ order_item.product.get_url }}">
                        <img src="{{ order_item.product.images.url }}" alt="Product image">
                      </a>
                    </figure>

                    <h3 class="product-title">
                      <a href="{{ order_item.product.get_url }}">{{ order_item.product }}</a>
                    </h3><!-- End .product-title -->
                  </div><!-- End .product -->
                </td>
                <td class="quantity-col">x {{ order_item.quantity }}</td>
                <td class="price-col">
                  {% if order_item.product.discount_price %}
                  <span class="new-price">{{ order_item.product.discount_price|intcomma }} đ</span>
                  <span class="old-price">{{ order_item.product.price|intcomma }} đ</span>
                  {% else %}
                  {{ order_item.product.price|intcomma }} đ
                  {% endif %}
                </td>
              </tr>
              {% endfor %}

            </tbody>
          </table><!-- End .table table-orders -->
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

  {% else %}

  <p>No order has been made yet.</p>
  <a href="{% url 'store' %}" class="btn btn-outline-primary-2">
    <span>GO SHOP</span>
    <i class="icon-long-arrow-right"></i>
  </a>

  {% endif %}
</div><!-- .End .tab-pane -->